-- FRIEND TABLE & SEQ DROP & CREATE
DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 9999;
CREATE TABLE FRIEND(
        NO NUMBER(4,0) PRIMARY KEY,
        NAME VARCHAR2(30) NOT NULL,
        TEL VARCHAR2(30)
    );
    -- 친구 전부 가져오기
   SELECT * FROM FRIEND;
    -- 친구 추가
   INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, '홍길동','010-9999-9999');
    -- 친구 검색
    SELECT * FROM FRIEND WHERE NAME LIKE '%'||'길'||'%' AND TEL LIKE '%'||'9999'||'%';
    COMMIT;